/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GameMasterPanel.java
 *
 * Created on Nov 7, 2010, 3:13:39 AM
 */

package aseprojectappclient;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;
import session.GameEntityFacadeRemote;

/**
 *
 * @author Andrew
 */
public class GameMasterPanel extends javax.swing.JPanel {

    GameEntityFacadeRemote gameSession;

    /** Creates new form GameMasterPanel */
    public GameMasterPanel() {
        initComponents();
        gameSession = lookupGameEntityFacadeRemote();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        initBoardButton = new javax.swing.JButton();

        initBoardButton.setText("Initialize Board");
        initBoardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                initBoardButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(initBoardButton)
                .addContainerGap(148, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(initBoardButton)
                .addContainerGap(215, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void initBoardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_initBoardButtonActionPerformed
        gameSession.initGameBoard();
    }//GEN-LAST:event_initBoardButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton initBoardButton;
    // End of variables declaration//GEN-END:variables

    private GameEntityFacadeRemote lookupGameEntityFacadeRemote() {
    try {
        Context c = new InitialContext();
        return (GameEntityFacadeRemote) c.lookup("java:global/aseProject/aseProject-ejb/GameEntityFacade");
    } catch (NamingException ne) {
        Logger.getLogger(getClass().getName()).log(Level.SEVERE, "exception caught", ne);
        throw new RuntimeException(ne);
    }
}

}
